version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app/api
      - ./indexer:/app/indexer
      - ./search:/app/search
      - ./patents_json:/app/patents_json


  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./indexer:/app/indexer
      - ./patents_json:/app/patents_json
  search:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./search:/app/search
